# Generated by Django 4.2.7 on 2023-11-28 18:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('type', models.CharField(choices=[('com', 'Commercial'), ('res', 'Residential'), ('ind', 'Industrial')], max_length=3, verbose_name='Type of construction project')),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pendin', 'Awaiting Approval'), ('inprog', 'In Progress'), ('comptd', 'Completed')], default='pendin', max_length=6)),
                ('project_subscription_arn', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
                'ordering': ['-created_at'],
                'permissions': [('manage_members', 'Can add or remove members'), ('manage_files', 'Can add or remove files'), ('review_files', 'Can approve file')],
            },
        ),
    ]
