# Generated by Django 4.2.7 on 2023-11-04 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='identifier',
            field=models.CharField(default='INIT', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 11, 4)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('com', 'Commercial'), ('res', 'Residential'), ('ind', 'Industrial')], default='com', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pendin', 'Pending'), ('inprog', 'In Progress'), ('comptd', 'Completed')], default='pendin', max_length=6),
        ),
    ]
