# Generated by Django 4.2.7 on 2023-11-12 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'permissions': [('manage_members', 'Can add or remove members'), ('manage_files', 'Can add or remove files')], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
