# Generated by Django 4.2.7 on 2023-11-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_subscription_arn',
            field=models.CharField(blank=True),
        ),
    ]
