# Generated by Django 4.2.7 on 2023-11-28 18:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Budget and Financial Documents', 'Budget and Financial Documents'), ('Contracts and Legal Documents', 'Contracts and Legal Documents'), ('Project Plans and Blueprints', 'Project Plans and Blueprints'), ('Material and Equipment Specifications', 'Material and Equipment Specifications'), ('Progress Reports and Logs', 'Progress Reports and Logs'), ('Safety Plans and Compliance Documents', 'Safety Plans and Compliance Documents'), ('Training Materials', 'Training Materials')], max_length=150)),
                ('versions', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Project File',
                'verbose_name_plural': 'Project Files',
                'db_table': 'project_files',
                'ordering': ['-created_at'],
            },
        ),
    ]
