# Generated by Django 4.2.7 on 2023-11-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='category',
            field=models.CharField(choices=[('Budget and Financial Documents', 'Budget and Financial Documents'), ('Contracts and Legal Documents', 'Contracts and Legal Documents'), ('Project Plans and Blueprints', 'Project Plans and Blueprints'), ('Material and Equipment Specifications', 'Material and Equipment Specifications'), ('Progress Reports and Logs', 'Progress Reports and Logs'), ('Safety Plans and Compliance Documents', 'Safety Plans and Compliance Documents'), ('Training Materials', 'Training Materials')], default='Budget and Financial Documents'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='versions',
            field=models.JSONField(default=dict),
        ),
    ]
