# Generated by Django 4.2.7 on 2023-11-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
