# Generated by Django 4.2.7 on 2023-11-11 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_projectfile_category_alter_projectfile_versions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectfile',
            options={'ordering': ['created_at'], 'verbose_name': 'Project File', 'verbose_name_plural': 'Project Files'},
        ),
        migrations.AlterModelTable(
            name='projectfile',
            table='project_files',
        ),
    ]
