# Generated by Django 4.2.7 on 2023-11-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_projectfile_options_alter_projectfile_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectfile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Project File', 'verbose_name_plural': 'Project Files'},
        ),
        migrations.AddField(
            model_name='projectfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
