# Generated by Django 4.2.7 on 2023-11-12 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_alter_project_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('PM', 'Project Manager'), ('ARCH', 'Architect'), ('CE', 'Civil Engineer'), ('SE', 'Structural Engineer'), ('CM', 'Construction Manager'), ('QS', 'Quantity Surveyor'), ('SENG', 'Site Engineer'), ('HSO', 'Health and Safety Officer'), ('ELEC', 'Electrician'), ('PLUM', 'Plumber'), ('MAS', 'Mason'), ('CARP', 'Carpenter'), ('HEO', 'Heavy Equipment Operator'), ('LS', 'Land Surveyor'), ('EC', 'Environmental Consultant'), ('ID', 'Interior Designer'), ('MECHENG', 'Mechanical Engineer'), ('ME', 'Materials Engineer'), ('QC', 'Quality Control'), ('INSPEC', 'Inspector'), ('LANS', 'Landscaper')], max_length=50)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'db_table': 'project_members',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='members',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='unique_project_user'),
        ),
    ]
