# Generated by Django 4.2.7 on 2023-11-28 18:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('PM', 'Project Manager'), ('ARCH', 'Architect'), ('CE', 'Civil Engineer'), ('SE', 'Structural Engineer'), ('CM', 'Construction Manager'), ('QS', 'Quantity Surveyor'), ('SENG', 'Site Engineer'), ('HSO', 'Health and Safety Officer'), ('ELEC', 'Electrician'), ('PLUM', 'Plumber'), ('MAS', 'Mason'), ('CARP', 'Carpenter'), ('HEO', 'Heavy Equipment Operator'), ('LS', 'Land Surveyor'), ('EC', 'Environmental Consultant'), ('ID', 'Interior Designer'), ('MECHENG', 'Mechanical Engineer'), ('ME', 'Materials Engineer'), ('QC', 'Quality Control'), ('INSPEC', 'Inspector'), ('LANS', 'Landscaper')], max_length=50)),
                ('subscription_arn', models.CharField(blank=True, max_length=255)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'db_table': 'project_members',
                'ordering': ['joined_at'],
            },
        ),
    ]
